### Task 1: Import pandas

In [1]:
import pandas as pd
print(pd.__version__)

2.3.3

### Task 2: Load the Customers Dataset

In [14]:
customers = pd.read_csv('data/Customer_Dataset.csv ')
customers

           age         income  visits_per_month
0    30.483571   33893.885591          9.295377
1    35.615149   33126.773002          7.531726
2    35.896064   41139.477833          7.061051
3    30.712800   31292.658458          7.068540
4    29.209811   19693.758043          4.550164
..         ...            ...               ...
295  67.926951  103758.922780          2.640708
296  59.134584  111630.553709          3.820482
297  58.550918  111000.120344          4.169296
298  64.675113  104730.648314          2.832882
299  56.026996  113097.634498          2.183064

[300 rows x 3 columns]

### Task 3: Preview the Customers Data

In [20]:
customers.head(6)

         age        income  visits_per_month
0  30.483571  33893.885591          9.295377
1  35.615149  33126.773002          7.531726
2  35.896064  41139.477833          7.061051
3  30.712800  31292.658458          7.068540
4  29.209811  19693.758043          4.550164
5  25.188562  26897.351037          8.628495

In [22]:
customers.tail(4)

           age         income  visits_per_month
296  59.134584  111630.553709          3.820482
297  58.550918  111000.120344          4.169296
298  64.675113  104730.648314          2.832882
299  56.026996  113097.634498          2.183064

In [25]:
customers.sample(5)

           age         income  visits_per_month
210  43.152748  117943.254792          2.841992
193  46.862524   69061.956890          4.377068
80   24.037396   34082.108468          9.009975
192  41.413687   74250.382327          2.782121
235  59.242070   75793.559713          4.754794

Q: do random rows look different every time its run?
A: Yes, because it picks random samples

### Task 4: Load and inspect the cars dataset

In [26]:
cars = pd.read_csv("data/cars.csv")